### ISSUE TITLE
No Links Found by the Crawler

### ISSUE THREAD

**Issue by ThesisCoacher** [NISH1001/medium-crawler#3]
Hey

I tried to use your Medium Cralwer on GitHub to collect some posts of a specific user.
 
However, the script runs smoothly. But in the output folder there is just a screenshot of the profile I would like to crawl…

Do I made a mistake or is the code outdated?

Thanks in advance :)

**Comment by NISH1001** [comment]
@ThesisCoacher 
I have updated the parser with new regular expression pattern. Can you give it a try again and reply here?
I have tested the new code and now it's fetching all the posts.

Cheers...

**Comment by ThesisCoacher** [comment]
@NISH1001 Thanks for the quick adjustments... 

Got the following traceback: 

`(base) D:\Issue Coverage FS2019\03_Datenbeschaffung\03_Scrapy\03_Medium\2\medium-crawler>python mcrawler.py -u nishparadox -t text -dd data/
Crawling for user :: nishparadox

DevTools listening on ws://127.0.0.1:65094/devtools/browser/b783bc51-d7b5-4f7e-8d8f-6267b6aee1d3
Using driver type :: headless
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Preparing to fetch available links...
Total Number of links :: 51
Getting :: https://medium.com/@nishparadox/when-nature-calls-aed621b11483?source=---------36------------------
Filename :: data/2017-06-27T05:35:26.490Z-When-Nature-Calls...
Traceback (most recent call last):
  File "mcrawler.py", line 108, in <module>
    main()
  File "mcrawler.py", line 105, in main
    run(args)
  File "mcrawler.py", line 101, in run
    run_crawler(args.user, args.type, args.dump_dir)
  File "mcrawler.py", line 98, in run_crawler
    dfunc(post, dump_dir)
  File "D:\Issue Coverage FS2019\03_Datenbeschaffung\03_Scrapy\03_Medium\2\medium-crawler\postutils.py", line 16, in save_post_as_text
    with open(fname, 'w') as f:
OSError: [Errno 22] Invalid argument: 'data/2017-06-27T05:35:26.490Z-When-Nature-Calls...'

(base) D:\Issue Coverage FS2019\03_Datenbeschaffung\03_Scrapy\03_Medium\2\medium-crawler>`

**Comment by NISH1001** [comment]
Oh, it seems like you are using windows for which path separator is "\" unlike for unix-like system which is "/".
I will refactor it with OS aware path separator.

**Comment by NISH1001** [comment]
@ThesisCoacher 
I have updated the code with new path tool that makes use of os module to join base directory (which is **dir**) with the corresponding filename of the post.

**Comment by ThesisCoacher** [comment]
Maybe I am wrong but I am still getting the same Traceback... I think its because of the name of the file... on windows filenames should not include ":" How can I fix this issue?

**Comment by NISH1001** [comment]
Perhaps, there might be some limited character set that windows supports. 
Meanwhile you can look into this specific line:
https://github.com/NISH1001/medium-crawler/blob/master/postutils.py#L14
Especially, the second argument to `join()`.

And add some preprocessing function to remove those "nasty" characters from the filename...

I have tested the code in my Linux system. It works. For windows, I have to work on the filename part which might take time. So, perhaps, you might fork and add a preprocess function which shouldn't be problem. I might be able to add that after few days!

:)

**Comment by ThesisCoacher** [comment]
Merci :)
